name: Gcovr Action
description: Generate code coverage reports for a C++ project using gcovr
author: Alfi Maulana
branding:
  color: green
  icon: check-circle
inputs:
  root:
    description: Root directory of your source files
  gcov-executable:
    description: Use a particular gcov executable
  excludes:
    description: Exclude source files that match these filters
  fail-under-line:
    description: Fail if the total line coverage is less than this value
  xml-out:
    description: Output file of the generated XML coverage report
  coveralls-out:
    description: Output file of the generated Coveralls API coverage report
  coveralls-send:
    description: Send the generated Coveralls API coverage report to it's endpoint (true/false)
    default: false
  github-token:
    description: GitHub token of your project
runs:
  using: node20
  main: dist/index.mjs
