name: Gcovr Action
author: Alfi Maulana
description: Generate code coverage reports for a C++ project using gcovr
branding:
  icon: check-circle
  color: green
inputs:
  root:
    description: Root directory of your source files
  gcov-executable:
    description: Use a particular gcov executable
  excludes:
    description: Exclude source files that match these filters
  fail-under-line:
    description: Fail if the total line coverage is less than this value
  fail-under-branch:
    description: Fail if the total branch coverage is less than this value
  fail-under-function:
    description: Fail if the total function coverage is less than this value
  html-out:
    description: Output file of the generated HTML coverage report
  html-theme:
    description: Override the default color theme for the HTML report. Default is green. Possible options green, blue, github.blue, github.green, github.dark-green, github.dark-blue
  xml-out:
    description: Output file of the generated XML coverage report
  coveralls-out:
    description: Output file of the generated Coveralls API coverage report
  coveralls-send:
    description: Send the generated Coveralls API coverage report to it's endpoint (true/false)
    default: false
  github-token:
    description: GitHub token of your project
    default: ${{ github.token }}
  working-directory:
    description: Working directory where gcovr should be executed from
runs:
  using: node20
  main: dist/index.js
